twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        uploads_dir: '%uploads_dir%'
        images_projet_dir: '%images_projet_dir%'
        images_techno_dir: '%images_techno_dir%'
        pdf_cv_dir: '%pdf_cv_dir%'
        recaptcha_site_key: '%recaptcha_site_key%'

when@test:
    twig:
        strict_variables: true

